apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "164"
    field.cattle.io/publicEndpoints: '[{"addresses":["172.17.0.4"],"port":443,"protocol":"HTTPS","serviceName":"default:portal","ingressName":"default:cgi-prod","hostname":"insights.contguard.com","path":"/","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-default-portal"},"name":"portal","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-default-portal"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"workload.user.cattle.io/workloadselector":"deployment-default-portal"}},"spec":{"containers":[{"env":[{"name":"BACKEND_URL","value":"https://insights.contguard.com"}],"image":"contguardregistry.azurecr.io/portal2:kubedeploy_v46","imagePullPolicy":"Always","name":"portal","ports":[{"containerPort":80,"name":"80tcp01","protocol":"TCP"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":false},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"contguardregistry"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}'
  creationTimestamp: "2020-07-12T06:06:08Z"
  generation: 176
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-portal
  name: portal
  namespace: default
  resourceVersion: "222144898"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/portal
  uid: 7b9d1a66-4ca4-4cfa-addd-fc7624e2e6e6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-portal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-09-29T13:15:27Z"
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"portal","hostPort":0,"kind":"ClusterIP","name":"80tcp02","protocol":"TCP","sourcePort":0},{"containerPort":8080,"dnsName":"portal","hostPort":0,"kind":"ClusterIP","name":"nginx8080","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-portal
    spec:
      containers:
      - env:
        - name: BACKEND_URL
          value: https://insights.contguard.com
        image: contguardregistry.azurecr.io/cg-main-webapp:87
        imagePullPolicy: Always
        name: portal
        ports:
        - containerPort: 80
          name: 80tcp02
          protocol: TCP
        - containerPort: 8080
          name: nginx8080
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: contguardregistry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-10-29T18:08:47Z"
    lastUpdateTime: "2022-10-29T18:08:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-08-24T06:02:31Z"
    lastUpdateTime: "2022-12-06T09:44:23Z"
    message: ReplicaSet "portal-6b4f65bf6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 176
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
