name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  Build:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Production Environment..."
          # Add your deployment command here
